export * from './stubTrue';
export * from './stubArray';
export * from './stubFalse';
export * from './stubObject';
export * from './stubString';
export * from './constant';
export * from './defaultTo';
export * from './uniqueId';
export * from './range';
export * from './rangeRight';
export * from './times';
export * from './nthArg';
export * from './property';
export * from './propertyOf';
export * from './matches';
export * from './matchesProperty';
export * from './iteratee';
export * from './method';
export * from './methodOf';
export * from './result';
export * from './attempt';
export * from './cond';
export * from './conforms';
export * from './conformsTo';
export * from './over';
export * from './overEvery';
export * from './overSome';

import * as stubTrue from './stubTrue';
import * as stubArray from './stubArray';
import * as stubFalse from './stubFalse';
import * as stubObject from './stubObject';
import * as stubString from './stubString';
import * as constant from './constant';
import * as defaultTo from './defaultTo';
import * as uniqueId from './uniqueId';
import * as range from './range';
import * as rangeRight from './rangeRight';
import * as times from './times';
import * as nthArg from './nthArg';
import * as property from './property';
import * as propertyOf from './propertyOf';
import * as matches from './matches';
import * as matchesProperty from './matchesProperty';
import * as iteratee from './iteratee';
import * as method from './method';
import * as methodOf from './methodOf';
import * as result from './result';
import * as attempt from './attempt';
import * as cond from './cond';
import * as conforms from './conforms';
import * as conformsTo from './conformsTo';
import * as over from './over';
import * as overEvery from './overEvery';
import * as overSome from './overSome';
export const utils = { ...stubTrue, ...stubArray, ...stubFalse, ...stubObject, ...stubString, ...constant, ...defaultTo, ...uniqueId, ...range, ...rangeRight, ...times, ...nthArg, ...property, ...propertyOf, ...matches, ...matchesProperty, ...iteratee, ...method, ...methodOf, ...result, ...attempt, ...cond, ...conforms, ...conformsTo, ...over, ...overEvery, ...overSome };
